import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ThemeToggler } from '@/components/theme-toggler'
import { ThemeProvider } from '@/providers/theme-provider'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          themes={['light', 'dark', 'neon']}
        >
          {children}

          <div className='absolute top-2 right-2'>
            <ThemeToggler />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
